list=[1,2,3,4,5]
print("original list is ",list)
print("first element is ",list[0])
print("last element is ",list[-1])
list[1]=25
print("updated list is ",list)
list.append(9)
print("after append list is ",list)
list.insert(2,30)
print("after inserting in to index 2 list is ",list)
list.extend([11,12])
print("after extend : ",list)
list.remove(4)
print("after removing 4 : ",list)
pop_item=list.pop()
print("popped item : ",pop_item)
print("after pop : ",list)
print("index of 3 is : ",list.index(3))
list.sort()
print("sorted list is : ",list)
list.reverse()
print("reversed list is : ",list)
print("length os list is : ",len(list))
list.clear()
print("after clearing : ",list)
